[2025-03-23T13:31:25.161+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: healthcare_claims_pipeline.create_database_tables manual__2025-03-23T13:26:09.691817+00:00 [queued]>
[2025-03-23T13:31:25.173+0000] {taskinstance.py:1157} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: healthcare_claims_pipeline.create_database_tables manual__2025-03-23T13:26:09.691817+00:00 [queued]>
[2025-03-23T13:31:25.174+0000] {taskinstance.py:1359} INFO - Starting attempt 2 of 2
[2025-03-23T13:31:25.192+0000] {taskinstance.py:1380} INFO - Executing <Task(PythonOperator): create_database_tables> on 2025-03-23 13:26:09.691817+00:00
[2025-03-23T13:31:25.198+0000] {standard_task_runner.py:57} INFO - Started process 541 to run task
[2025-03-23T13:31:25.201+0000] {standard_task_runner.py:84} INFO - Running: ['***', 'tasks', 'run', 'healthcare_claims_pipeline', 'create_database_tables', 'manual__2025-03-23T13:26:09.691817+00:00', '--job-id', '14', '--raw', '--subdir', 'DAGS_FOLDER/healthcare_claims_dag.py', '--cfg-path', '/tmp/tmpmxm6k9ux']
[2025-03-23T13:31:25.203+0000] {standard_task_runner.py:85} INFO - Job 14: Subtask create_database_tables
[2025-03-23T13:31:25.269+0000] {task_command.py:415} INFO - Running <TaskInstance: healthcare_claims_pipeline.create_database_tables manual__2025-03-23T13:26:09.691817+00:00 [running]> on host f14adedb7c2a
[2025-03-23T13:31:25.373+0000] {taskinstance.py:1660} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='healthcare_claims_pipeline' AIRFLOW_CTX_TASK_ID='create_database_tables' AIRFLOW_CTX_EXECUTION_DATE='2025-03-23T13:26:09.691817+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-03-23T13:26:09.691817+00:00'
[2025-03-23T13:31:25.386+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-03-23T13:31:25.391+0000] {logging_mixin.py:151} INFO - Database 'claims' already exists
[2025-03-23T13:31:25.399+0000] {base.py:73} INFO - Using connection ID 'postgres_default' for task execution.
[2025-03-23T13:31:25.404+0000] {logging_mixin.py:151} INFO - Creating raw_inpatient_claims table...
[2025-03-23T13:31:25.412+0000] {logging_mixin.py:151} INFO - Creating patient_claims_plus table...
[2025-03-23T13:31:25.426+0000] {logging_mixin.py:151} INFO - Database tables created successfully
[2025-03-23T13:31:25.426+0000] {python.py:194} INFO - Done. Returned value was: Database tables created
[2025-03-23T13:31:25.449+0000] {taskinstance.py:1398} INFO - Marking task as SUCCESS. dag_id=healthcare_claims_pipeline, task_id=create_database_tables, execution_date=20250323T132609, start_date=20250323T133125, end_date=20250323T133125
[2025-03-23T13:31:25.498+0000] {local_task_job_runner.py:228} INFO - Task exited with return code 0
[2025-03-23T13:31:25.529+0000] {taskinstance.py:2776} INFO - 1 downstream tasks scheduled from follow-on schedule check
